name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  rust_min: 1.58.0

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.rust_min }}
      - name: Build no features
        run: cargo build --no-default-features
      - name: Run tests no features
        run: cargo test --no-default-features
      - name: Build
        run: cargo build
      - name: Run
        run: cargo test
      - name: Build all features
        run: cargo build --all-features
      - name: Run tests with all features
        run: cargo test --all-features